version: "3.8"

services:
  bot:
    build: 
      context: .
    networks:
      - backend
    command: >
      cargo run
    depends_on:
      - postgres
    volumes:
      - .:/app
  postgres:
    image: "postgres:latest"
    container_name: postgres
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5431:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
networks:
  backend:
